### ISSUE TITLE
 unrecognized import path "math/bits"

### ISSUE THREAD

**Issue by wifidoneright** [google/link022#89]
go get github.com/google/link022/agent
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

im following the start guide for the raspberry pi and get this error when trying to download the agent onto the raspberry pi

Raspberry Pi 3 
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

**Comment by boleifu** [comment]
Can you provide the version of Golang you are using? Thanks.

**Comment by wifidoneright** [comment]
pi@ocap:~ $ go version
go version go1.7 linux/arm

**Comment by boleifu** [comment]
Can you try go 1.10? It seems some dependency libraries requires newer version of Golang.

**Comment by wifidoneright** [comment]
Great. it looks like it is going now with the newer version.
thank you for your help

wget https://storage.googleapis.com/golang/go1.10.1.linux-armv6l.tar.gz
sudo tar -C /usr/local -xzf go1.10.1.linux-armv6l.tar.gz
