### ISSUE TITLE
error when starting the agent

### ISSUE THREAD

**Issue by wifidoneright** [google/link022#92]
i just installed stretch on this raspberry pi 3 and after following the readme for installing and running the agent i get the following error message, and I am unable to run the agent.
```cli
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
sudo env PATH=$PATH agent \
> -ca=/home/pi/tls_cert_key/server/ca.crt \
> -cert=/home/pi/tls_cert_key/server/server.crt \
> -key=/home/pi/tls_cert_key/server/server.key \
> -eth_intf_name=eth0 \
> -wlan_intf_name=wlan0 \
> -gnmi_port=10162
```
```cli
panic: schema error: json: cannot unmarshal object into Go struct field ListAttr.Dir.Dir.Dir.Dir.Dir.Dir.Dir.ListAttr.MaxElements of type uint64

goroutine 1 [running]:
github.com/google/link022/generated/ocstruct.init.0()
	/home/pi/go/src/github.com/google/link022/generated/ocstruct/ocstruct.go:37 +0xd4
```
go version go version go1.15 linux/arm

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by mike-albano** [comment]
While this repo served as a great resource for implementors of OC/gNMI when we were getting started, it is not actively maintained.
For a good affordable implementation example, suggest purchasing a real AP which supports OC/gNMI (Such as Arista C-130).

**Comment by wifidoneright** [comment]
it is a very interesting repo and i appreciate all it has. Thank you. I will look into that AP.

**Comment by ramonfontes** [comment]
Hello,

I made some changes in the codes and I was able to successfully make it work. I've been doing some tests with [Mininet-WiFi](https://github.com/intrig-unicamp/mininet-wifi) and both hostapd and monitoring agents are working as expected.

https://github.com/ramonfontes/link022
